scalar:
    # accuracy:
    #   _target_: torchmetrics.functional.classification.binary_accuracy
    # auc_roc:
    #   _target_: torchmetrics.functional.classification.binary_auroc
    # avg_precision:
    #   _target_: torchmetrics.functional.classification.binary_average_precision
    # recall:
    #   _target_: torchmetrics.functional.classification.binary_recall
    # precision:
    #   _target_: torchmetrics.functional.classification.binary_precision
    accuracy:
      _target_: torchmetrics.functional.classification.accuracy
      task: multiclass
      num_classes: 2
    auc_roc:
      _target_: torchmetrics.functional.classification.auroc
      task: multiclass
      num_classes: 2
      average: macro
    avg_precision:
      _target_: torchmetrics.functional.classification.average_precision
      task: multiclass
      num_classes: 2
      average: macro
    recall:
      _target_: torchmetrics.functional.classification.recall
      task: multiclass
      num_classes: 2
      average: macro
    precision:
      _target_: torchmetrics.functional.classification.precision
      task: multiclass
      num_classes: 2
      average: macro
tuple:
  binary_roc:
    _target_: torchmetrics.functional.classification.binary_roc
  binary_pr:
    _target_: torchmetrics.functional.classification.binary_precision_recall_curve
